name: Build Xemu
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Build Xemu
        run: |
          docker run --rm --privileged aptman/qus -s -- -p arm aarch64    
          git clone https://github.com/George-Seven/Termux-XEMU
          mkdir -p Termux-XEMU/build-xemu
          git clone https://github.com/termux/termux-packages Termux-XEMU/build-xemu/termux-packages.backup
          cp -rf Termux-XEMU/build-xemu/termux-packages.backup Termux-XEMU/build-xemu/termux-packages
          touch Termux-XEMU/build-xemu/.termux-packages.backup
          git clone --recursive https://github.com/xemu-project/xemu Termux-XEMU/build-xemu/xemu.backup
          (
          cd Termux-XEMU/build-xemu/xemu.backup
          git remote add rebind https://github.com/antangelo/xemu
          git fetch rebind
          git cherry-pick 7eb8a0a238d50c4ba54757596475ab6fb3d2b315
          )
          cp -rf Termux-XEMU/build-xemu/xemu.backup Termux-XEMU/build-xemu/xemu
          touch Termux-XEMU/build-xemu/.xemu.backup
          docker run --name=build-xemu -t --privileged -v $(pwd)/Termux-XEMU:/data/data/com.termux/files/home/Termux-XEMU.backup termux/termux-docker:aarch64 bash -c 'export TERM="xterm-256color" && cp -rf Termux-XEMU.backup Termux-XEMU && cd Termux-XEMU && ./build-xemu.sh'
          docker cp build-xemu:/data/data/com.termux/files/home/Termux-XEMU/build-xemu/xemu.deb $(pwd)/Termux-XEMU/build-xemu/xemu.deb

      - name: Upload Release
        uses: svenstaro/upload-release-action@v2
        with:
           repo_token: ${{ secrets.GITHUB_TOKEN }}
           file: "Termux-XEMU/build-xemu/xemu.deb"
           asset_name: "xemu-arm64.deb"
           tag: "xemu"
           release_name: "Xemu Original Xbox emulator for Termux"
           overwrite: true
